name: zapdefiapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  modal_bottom_sheet: ^2.0.0
  kiwi: ^4.0.1
  auto_route: ^4.2.0
  path_provider: ^2.0.6
  provider: ^6.0.1
  dio: ^4.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphite: ^0.3.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.4
  auto_route_generator: ^4.2.0
  kiwi_generator: ^4.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
